root: true
ignorePatterns:
  - '!**/*'
plugins:
  - '@nx'
  - unused-imports
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - plugin:@nx/typescript
    rules:
      '@typescript-eslint/no-unused-vars': off
      '@typescript-eslint/no-extra-semi': off
      '@typescript-eslint/no-empty-function': off
      '@typescript-eslint/no-non-null-assertion': off
      react-hooks/exhaustive-deps: off
      unused-imports/no-unused-imports: warn
      unused-imports/no-unused-vars:
        - warn
        - vars: all
          varsIgnorePattern: ^_
          args: after-used
          argsIgnorePattern: ^_
  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - plugin:@nx/javascript
    rules: {}
extends:
  - plugin:@nx/react
